### ISSUE TITLE
Cite sources?

### ISSUE THREAD

**Issue by AWSChad** [aws-samples/bedrock-claude-chat#118] opened 2024-02-18 21:46 UTC
Hi, similar to Bedrock Knowledge Bases or Amazon Q, there should be an option for Bedrock Claude Chat to cite sources for its responses. This would offer much great confidence in the quality of the responses.

**Comment by statefb** [comment] 2024-02-19 01:08
Duplicate of #108

**Closed** 2024-04-03 09:06 UTC
