### ISSUE TITLE
[BUG] error when upload file to chat 

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#433] opened 2024-07-09 08:37 UTC
## Describe the bug

I tried to attach file .md or .log to the chat but getting error as mentioned in the pictures below. until you press resend then the whole content of file is printed on screen 

## To Reproduce

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

1. Go to new chat
2. Click on attach file 
3. select .md/.log 
4. getting error all the time but when i make resend the whole content is printed on the screen then it works 

## Screenshots

ATTACHED

<img width="1501" alt="Screenshot 2024-07-09 at 10 48 50" src="https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/67bd4006-99a7-4dab-bca4-823e48835f7d">
<img width="645" alt="Screenshot 2024-07-09 at 10 49 01" src="https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/428741dd-fd69-48b0-9362-1a1dd6fbc6ec">

**Comment by statefb** [comment] 2024-07-09 08:57
I couldn't reproduce that. Please describe reproduction steps more precisely as much as possible.

**Comment by DTheunis** [comment] 2024-07-25 13:13
We have the same issue - uploading any file to a bot WITHOUT knowledge will first throw an error, until you click 'Resend', then the file content will be output to the chat and the chat will respond.

After sending a file:
![afbeelding](https://github.com/user-attachments/assets/da701f55-c3c2-4d7a-a86a-ab2bbf3e7bd3)


After pressing Resend:
![afbeelding](https://github.com/user-attachments/assets/150ba64c-1056-484e-a55c-f795b8b34087)



I'm using this file as example:
[dummy.txt](https://github.com/user-attachments/files/16378190/dummy.txt)

**Comment by DTheunis** [comment] 2024-07-25 13:19
See below for a screen recording:

![claudebug](https://github.com/user-attachments/assets/26a890e7-2bff-4af5-9d94-cb8b67f95e06)

**Comment by statefb** [comment] 2024-07-26 02:59
@DTheunis We're enhancing this feature to handle non-text file on #467, and will be merged soon. Your attachment dummy.txt works on the branch. I'd be glad if you could wait the merge.

**Comment by DTheunis** [comment] 2024-07-26 10:02
I'm having the same issue with the latest version.
(I think you can tell it's the latest version since the content of the file is now encoded rather than fully printed to the chat)
![claudebug](https://github.com/user-attachments/assets/1eed5ac6-df89-4b7a-ae1a-ebcf2c954c46)


FYI, this is what the console says when I upload the file initially:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    onmessage https://claude.cloudar.be/assets/index-6ae23883.js:349
    post https://claude.cloudar.be/assets/index-6ae23883.js:349
    post https://claude.cloudar.be/assets/index-6ae23883.js:349
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    J https://claude.cloudar.be/assets/index-6ae23883.js:676
    J https://claude.cloudar.be/assets/index-6ae23883.js:351
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    XNe https://claude.cloudar.be/assets/index-6ae23883.js:351
    I0 https://claude.cloudar.be/assets/index-6ae23883.js:40
    Ju https://claude.cloudar.be/assets/index-6ae23883.js:40
    $X https://claude.cloudar.be/assets/index-6ae23883.js:40
    Js https://claude.cloudar.be/assets/index-6ae23883.js:40
    cN https://claude.cloudar.be/assets/index-6ae23883.js:40
    Os https://claude.cloudar.be/assets/index-6ae23883.js:38
    Nl https://claude.cloudar.be/assets/index-6ae23883.js:40
    l9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Gb https://claude.cloudar.be/assets/index-6ae23883.js:37
    sT https://claude.cloudar.be/assets/index-6ae23883.js:37
    CZ https://claude.cloudar.be/assets/index-6ae23883.js:37
    U9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Hb https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    createRoot https://claude.cloudar.be/assets/index-6ae23883.js:40
    <anonymous> https://claude.cloudar.be/assets/index-6ae23883.js:678
[index-6ae23883.js:349:14405](https://claude.cloudar.be/assets/index-6ae23883.js)
    onmessage https://claude.cloudar.be/assets/index-6ae23883.js:349
    (Async: EventHandlerNonNull)
    post https://claude.cloudar.be/assets/index-6ae23883.js:349
    post https://claude.cloudar.be/assets/index-6ae23883.js:349
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    J https://claude.cloudar.be/assets/index-6ae23883.js:676
    J https://claude.cloudar.be/assets/index-6ae23883.js:351
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    (Async: EventListener.handleEvent)
    XNe https://claude.cloudar.be/assets/index-6ae23883.js:351
    I0 https://claude.cloudar.be/assets/index-6ae23883.js:40
    Ju https://claude.cloudar.be/assets/index-6ae23883.js:40
    $X https://claude.cloudar.be/assets/index-6ae23883.js:40
    Js https://claude.cloudar.be/assets/index-6ae23883.js:40
    cN https://claude.cloudar.be/assets/index-6ae23883.js:40
    Os https://claude.cloudar.be/assets/index-6ae23883.js:38
    Nl https://claude.cloudar.be/assets/index-6ae23883.js:40
    l9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Gb https://claude.cloudar.be/assets/index-6ae23883.js:37
    sT https://claude.cloudar.be/assets/index-6ae23883.js:37
    CZ https://claude.cloudar.be/assets/index-6ae23883.js:37
    (Async: EventListener.handleEvent)
    U9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Hb https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    createRoot https://claude.cloudar.be/assets/index-6ae23883.js:40
    <anoniem> https://claude.cloudar.be/assets/index-6ae23883.js:678
An error occurred while predicting. [index-6ae23883.js:351:9184](https://claude.cloudar.be/assets/index-6ae23883.js)
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    (Async: promise callback)
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    J https://claude.cloudar.be/assets/index-6ae23883.js:676
    J https://claude.cloudar.be/assets/index-6ae23883.js:351
    ne https://claude.cloudar.be/assets/index-6ae23883.js:351
    (Async: EventListener.handleEvent)
    XNe https://claude.cloudar.be/assets/index-6ae23883.js:351
    I0 https://claude.cloudar.be/assets/index-6ae23883.js:40
    Ju https://claude.cloudar.be/assets/index-6ae23883.js:40
    $X https://claude.cloudar.be/assets/index-6ae23883.js:40
    Js https://claude.cloudar.be/assets/index-6ae23883.js:40
    cN https://claude.cloudar.be/assets/index-6ae23883.js:40
    Os https://claude.cloudar.be/assets/index-6ae23883.js:38
    Nl https://claude.cloudar.be/assets/index-6ae23883.js:40
    l9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Gb https://claude.cloudar.be/assets/index-6ae23883.js:37
    sT https://claude.cloudar.be/assets/index-6ae23883.js:37
    CZ https://claude.cloudar.be/assets/index-6ae23883.js:37
    (Async: EventListener.handleEvent)
    U9 https://claude.cloudar.be/assets/index-6ae23883.js:37
    Hb https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    Bf https://claude.cloudar.be/assets/index-6ae23883.js:37
    createRoot https://claude.cloudar.be/assets/index-6ae23883.js:40
    <anoniem> https://claude.cloudar.be/assets/index-6ae23883.js:678`

**Comment by statefb** [comment] 2024-07-29 08:20
@DTheunis Let me check, have you tried [v1.2.7](https://github.com/aws-samples/bedrock-claude-chat/releases) and are you truly using the app without any customization and changes?

**Comment by sasanquaneuf** [comment] 2024-08-12 14:59
I had same issue with v1.2.7. There are no customizations or changes.
The resend button partially works but doesn't decode.
<img width="1150" alt="スクリーンショット 2024-08-12 23 54 41" src="https://github.com/user-attachments/assets/4a593932-cea1-4618-bb7d-437e922a6cd6">
<img width="1150" alt="スクリーンショット 2024-08-12 23 54 51" src="https://github.com/user-attachments/assets/3d983557-314d-4a30-815d-11ac198cc6f8">
<img width="1149" alt="スクリーンショット 2024-08-12 23 55 12" src="https://github.com/user-attachments/assets/bb9fc6ca-554b-4115-be0d-db51ace75387">
<img width="786" alt="スクリーンショット 2024-08-12 23 56 17" src="https://github.com/user-attachments/assets/e7569053-490a-468a-bd9e-550de2e4a248">

**Comment by statefb** [comment] 2024-08-13 05:35
Finally I found the cause. The reason failed is the model Sonnet 3.5 does not support file attachment at this moment. More info, please see the [doc](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html). To avoid this issue, use Claude 3 models rather than 3.5.

![Screenshot 2024-08-13 at 14 33 25](https://github.com/user-attachments/assets/efc83efb-8706-4d59-b53d-ab98bb49b3a1)

**Comment by sasanquaneuf** [comment] 2024-08-13 07:00
@statefb 
Thank you!
I tried the same file with Sonnet 3.0, and it worked. Thank you very much for checking.

**Comment by statefb** [comment] 2024-08-13 07:04
@sasanquaneuf Thank you for checking. Let me close this issue.

**Closed as completed by statefb** 2024-08-13 07:04 UTC
Labels: needs-info
